INSERT into "Source"
VALUES ('1', 'Tunisie Annonce', true, true),
       ('2', 'Tayara', true, true),
       ('3', 'Ballouchi', true, true),
       ('4', 'Facebook', true, true),
       ('5', 'Ahaya', true, true),
       ('6', 'Tanitjobs', false, false),
       ('7', 'Afariat', true, true),
       ('8', 'Tunisiapromo', true, true),
       ('9', 'Jumia Deals', true, true),
       ('10', 'DannousTn', true, true),
       ('11', 'Ijaelhouni', true, true),
       ('12', 'Keejob', false, false),
       ('13', 'Automobile.tn', true, true),
       ('14', 'Tunisie Travail', false, false),
       ('15', 'Mubawab', true, true),
       ('16', 'Affare', true, true),
       ('17', 'Fammech', true, true),
       ('18', 'emploi.nat.tn', false, false),
       ('19', 'Locanto', true, true),
       ('20', 'Sindibad', true, true),
       ('21', 'Houni.tn', true, true),
       ('22', 'Cava.tn', true, true),
       ('23', 'BnB Tunisie', true, true);

